export const ADD_CART_REQUEST = "ADD_CART_REQUEST";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_FAIL = "ADD_CART_FAIL";

export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAIL = "GET_CART_FAIL";

export const UPDATE_CART_REQUEST = "UPDATE_CART_REQUEST";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const UPDATE_CART_FAIL = "UPDATE_CART_FAIL";

export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";
export const DELETE_CART_FAIL = "DELETE_CART_FAIL";

export const SHIPPING_ADDRESS_REQUEST = "SHIPPING_ADDRESS_REQUEST";
export const SHIPPING_ADDRESS_SUCCESS = "SHIPPING_ADDRESS_SUCCESS";
export const SHIPPING_ADDRESS_FAIL = "SHIPPING_ADDRESS_FAIL";

export const GET_SHIPPING_ADDRESS = "GET_SHIPPING_ADDRESS";
export const GET_SHIPPING_ADDRESS_FAIL = "GET_SHIPPING_ADDRESS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
