export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";
export const ALL_PRODUCT_IMAGES_SUCCESS = "ALL_PRODUCT_IMAGES_SUCCESS";
export const ALL_PRODUCT_IMAGES_FAIL = "ALL_PRODUCT_IMAGES_FAIL";

export const ALL_CATEGORY_SUCCESS = "ALL_CATEGORY_SUCCESS";
export const ALL_CATEGORY_FAIL = "ALL_CATEGORY_FAIL";

export const REVIEWS_REQUEST = "REVIEWS_REQUEST";
export const REVIEWS_SUCCESS = "REVIEWS_SUCCESS";
export const REVIEWS_FAIL = "REVIEWS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
